name: anick_giroux
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  http: ^1.1.0
  intl: ^0.19.0
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.3.2
  go_router: ^13.2.0
  flutter_riverpod: ^2.5.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  uuid: ^4.4.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  lottie: ^3.3.2
  local_auth: ^2.3.0
  crypto: ^3.0.3

  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.5.0
  firebase_storage: ^12.4.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.4

  http_parser: any
  flutter_stripe: ^12.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1


flutter:


  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/onbording1.png
    - assets/images/onbording2.png
    - assets/images/onbording3.png
    - assets/images/loginpage_image.png
    - assets/images/icon/
    - assets/images/insurance/
    - assets/images/protected.png
    - assets/images/create.png
    - assets/images/upload.png
    - assets/images/update_delete.png
    - assets/images/createsubfolder.png
    - assets/images/pdficon.png
    - assets/images/black_delete.png
    - assets/images/black_download.png
    - assets/images/black_share.png
    - assets/images/lottie_Animation/
    - assets/images/
